# Dockerfile_flask

FROM python:3.9-slim

WORKDIR /app

# Instalar dependências
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código da aplicação
COPY app.py /app/
COPY entrypoint.sh /app/entrypoint.sh

# Garantir permissões de execução
RUN chmod +x /app/entrypoint.sh

# Definir o entrypoint
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["python", "app.py"]
