# Dockerfile_flask
FROM python:3.9-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia e instala dependências
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia o script da aplicação
COPY app.py /app/

# Copia o script wait-for-it para esperar o banco estar pronto
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Define variáveis de ambiente para o Flask
ENV FLASK_APP=app
ENV FLASK_ENV=development

# Comando para iniciar o Flask depois que o MariaDB estiver pronto
CMD ["/wait-for-it.sh", "mariadb:3306", "--", "flask", "run", "--host=0.0.0.0"]
