global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask_app_container:5000']

  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['mysqld_exporter_container:9104']
